# Utiliza una imagen base de Java
FROM openjdk:19
WORKDIR /app
COPY Reaktor-0.0.1-SNAPSHOT-jar-with-dependencies.jar .
EXPOSE 8084
CMD ["java", "-jar", "Reaktor-0.0.1-SNAPSHOT-jar-with-dependencies.jar"]