spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/carritos
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8084